name: Build
on: workflow_dispatch
jobs:
  Windows:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout opus
        uses: actions/checkout@v4
        with:
          repository: xiph/opus
          ref: v1.4
          path: opus
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build opus
        run: |
          cd opus
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Debug
          cmake --install . --config Debug --prefix install/Debug
          cmake --build . --config Release
          cmake --install . --config Release --prefix install/Release
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./opus/build/install/*,./Release.txt -DestinationPath opus.win.${{ github.ref_name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: opus.win.${{ github.ref_name }}.zip
  Linux:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout opus
        uses: actions/checkout@v4
        with:
          repository: xiph/opus
          ref: v1.4
          path: opus
      - name: Install deps
        run: |
          sudo apt-get -y install gcc-10 g++-10
      - name: Build
        run: |
          alias gcc='gcc-10'
          alias g++='g++-10'
          export CC=`which gcc-10`
          export CXX=`which g++-10`
          cd opus
          mkdir build
          cd build
          cmake .. -B Release -DCMAKE_BUILD_TYPE=Release
          cmake --build Release
          cmake --install Release/ --prefix install/Release
      - name: Generate tar
        run: |
          echo ${{ github.sha }} > Release.txt
          cp Release.txt ./opus/build/install/Release
          tar -czvf opus.linux.${{ github.ref_name }}.tar.gz -C ./opus/build/install/Release .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: opus.linux.${{ github.ref_name }}.tar.gz
  macOS:
    permissions:
      contents: write
    runs-on: macos-14
    steps:
      - name: Checkout opus
        uses: actions/checkout@v4
        with:
          repository: xiph/opus
          ref: v1.4
          path: opus
      - name: Build
        run: |
          cd opus
          mkdir build
          cd build
          cmake .. -B Release -DCMAKE_BUILD_TYPE=Release
          cmake --build Release
          cmake --install Release/ --prefix install/Release
      - name: Generate tar
        run: |
          echo ${{ github.sha }} > Release.txt
          cp Release.txt ./opus/build/install/Release
          tar -czvf opus.macos.${{ github.ref_name }}.tar.gz -C ./opus/build/install/Release .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: opus.macos.${{ github.ref_name }}.tar.gz