name: Windows
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout opus
        uses: actions/checkout@v4
        with:
          repository: xiph/opus
          ref: v1.4
          path: opus
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build opus
        run: |
          cd opus
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Debug
          cmake --install . --config Debug --prefix install/Debug
          cmake --build . --config Release
          cmake --install . --config Release --prefix install/Release
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./opus/build/install/*,./Release.txt -DestinationPath opus.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: opus.zip